### ISSUE TITLE
Wrong paths in recipe

### ISSUE THREAD

**Issue by alrf** [chef-cookbooks/jetty#12]
line 44
https://github.com/chef-cookbooks/jetty/blob/master/recipes/default.rb

line 35
https://github.com/chef-cookbooks/jetty/blob/master/attributes/default.rb

As result, I have:
    Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jetty/recipes/default.rb:44:in `from_file'

           template("/etc/jetty/jetty.xml") do
             action "create"
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             path "/etc/jetty/jetty.xml"
             backup 5
             atomic_update true
             source "jetty.xml.erb"
             declared_type :template
             cookbook_name "jetty"
             recipe_name "default"
             mode "0644"
             owner "root"
             group "root"
           end

         * service[jetty] action restart
           - restart service service[jetty]

       Running handlers:
       [2015-11-12T13:04:19+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-12T13:04:19+00:00] ERROR: Exception handlers complete
       [2015-11-12T13:04:19+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 3 resources updated in 36.716688919 seconds
       [2015-11-12T13:04:19+00:00] ERROR: template[/etc/jetty/jetty.xml] (jetty::default line 44) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/jetty does not exist.

Because filename is hardcoded in recipe..
I use CentOS 6, RHEL platform, path should be: set['jetty']['config_dir'] = '/etc/jetty6'

Why do you not use attributes?

**Comment by tas50** [comment]
This will be fixed in the 1.0 release by having all platforms use the .tar.gz for the latest platform. The need for the odd paths on RHEL with jetty6 goes away https://github.com/chef-cookbooks/jetty/issues/16
