### ISSUE TITLE
Support for Jetty 8

### ISSUE THREAD

**Issue by fehwalker** [chef-cookbooks/jetty#9]
There's a supported Jetty 8 package in newer Debian/Ubuntu releases, which is needed for any Servlet 3.0 apps -- the older Jetty 6 installed by default only supports Servlet 2.5.

**Comment by tas50** [comment]
I'm investigating either using the newer jetty packages or converting this cookbook to use the zip files so it's always current.  6 is obviously crazy outdated and also unsupported

**Comment by tas50** [comment]
This will be fixed by https://github.com/chef-cookbooks/jetty/issues/16 in the 1.0 release.
